# Basic workflow that:
# --> lints the markdown in the README file and all other Markdown files
# --> builds the PDF of the CV using latexmk compiler
name: build

# Controls when the action will run.
# Triggers the workflow on push or pull request
# events but only for the master branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic cv_obc.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: cv_obc
          path: cv_obc.pdf